### ISSUE TITLE
playbook_on_start() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by wiseflat** [rrey/ansible-callback-grafana-annotations#11]
Hello,

I would like to try this wonderful callback but I have a problem when I run my playbook :

```
 [WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback./ansible-project/plugins/callback/human_log.CallbackModule object at
0x10b5b8210>): playbook_on_start() takes exactly 1 argument (2 given)
```

This is a sample of my ansible.cfg :

```
[callback_grafana_annotations]

grafana_url = "https://grafana.mydomain.com/api/annotations"
validate_grafana_certs = 1
http_agent = ansible
grafana_api_key = 'alski89JkNBJVmNNYzhMUGNiN3cyd2t4OTAyUGtPWVdmejciLCJuIjoiYW5zaWJsZS1jYWxsYmFjayIsImlkIjoxxgS=='
```

Any ideas ?

Cheers

**Comment by rrey** [comment]
Hi @wiseflat!

What is your ansible version ?

**Comment by wiseflat** [comment]
Hi @rrey ,

Ansible version : 2.6.4

**Comment by wiseflat** [comment]
I followed instructions on your blog btw :-) 
https://blog.octo.com/en/walkthrough-watch-your-ansible-deployments-in-grafana/

**Comment by rrey** [comment]
> I followed instructions on your blog btw :-)

haaa maybe that the issue.
Did you download the code through wget like in the blog post ?

It's outdated, the variables were renamed after the callback was added in the Ansible project (2.6).
You should only enable the callback in ansible.cfg by adding it in the `callback_whitelist`.
You don't need to create the `callback_plugin` directory with the code anymore since the plugin is now part of Ansible.

The rest of the plugin conf in ansible.cfg seems correct to me.

**Comment by wiseflat** [comment]
Hello @rrey !

Ok I got it! I have a nice Grafana dashboard now ;-)
Thank you
